##
# Pokémon Trainers
##

ash:
  # 025
  pikachu:
    primary: '#F6BD20'
    secondary: '#4C1803'
    tertiary: '#DE7329'
    unibody: '#F7DE82'

  # 010
  caterpie:
    primary: '#F47B59'
    secondary: '#63583E'
    tertiary: '#F2DF9C'
    unibody: '#8CC979'

  # 011
  metapod:
    primary: '#77A052'
    secondary: '#230729'
    tertiary: '#DDFEAC'
    unibody: '#85B243'

  # 012
  butterfree:
    primary: '#7FBBC5'
    secondary: '#262330'
    tertiary: '#F4D89A'
    unibody: '#978DC1'

  # 016
  pidgey:
    primary: '#F3EAB7'
    secondary: '#0A0A08'
    tertiary: '#AC8992'
    unibody: '#9E6B35'

  # 017
  pidgeotto:
    primary: '#A3733C'
    secondary: '#C25046'
    tertiary: '#A48554'
    unibody: '#F7F3B0'

  # 001
  bulbasaur:
    primary: '#5B9C71'
    secondary: '#0F2C33'
    tertiary: '#F8DEA0'
    unibody: '#77AC98'

  # 004
  charmander:
    primary: '#96191B'
    secondary: '#35261D'
    tertiary: '#F6DFD1'
    unibody: '#F4B186'

  # 005
  charmeleon:
    primary: '#BE5B55'
    secondary: '#532924'
    tertiary: '#EAD3D1'
    unibody: '#D3675A'

  # 006
  charizard:
    primary: '#CF844B'
    secondary: '#4C1803'
    tertiary: '#DBD8AE'
    unibody: '#DC8E4C'

  # 007
  squirtle:
    primary: '#916A5B'
    secondary: '#832900'
    tertiary: '#B4E6EE'
    unibody: '#84C1D4'

  # 020
  raticate:
    primary: '#A28091'
    secondary: '#2E2300'
    tertiary: '#21C8D8'
    unibody: '#CB9652'

  # 128
  tauros:
    primary: '#6E6852'
    secondary: '#3D2914'
    tertiary: '#23809D'
    unibody: '#EAA763'

  # 143
  snorlax:
    primary: '#F5EF7C'
    secondary: '#1A2927'
    tertiary: '#40C9B2'
    unibody: '#4A736B'

  # 131
  lapras:
    primary: '#157397'
    secondary: '#00222E'
    tertiary: '#C26837'
    unibody: '#0793C6'

  # 098
  krabby:
    primary: '#E78A4F'
    secondary: '#292929'
    tertiary: '#367382'
    unibody: '#F4E5E0'

  # 099
  kingler:
    primary: '#D06628'
    secondary: '#306573'
    tertiary: '#43B28F'
    unibody: '#F2E0CA'

  # 057
  primeape:
    primary: '#F38C8D'
    secondary:  '#4A71B5'
    tertiary: '#3B2F42'
    unibody: '#F6E5C7'

  # 089
  muk:
    primary: '#775A92'
    secondary: '#23182E'
    tertiary: '#DEC9A0'
    unibody: '#8D6DAC'

brock:
  # 095
  onix:
    primary: '#4B494E'
    secondary: '#E8E8D6'
    tertiary: '#4E7378'
    unibody: '#9B9AA2'

  # 074
  geodude:
    primary: '#505833'
    secondary: '#382C00'
    tertiary: '#A6552D'
    unibody: '#B5A66D'

  # 041
  zubat:
    primary: '#874E83'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#5486A9'

  # 042
  golbat:
    primary: '#82487A'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#306E93'

  # 037
  vulpix:
    primary: '#723822'
    secondary: '#421402'
    tertiary: '#f2a485'
    unibody: '#c08672'

  # 038
  ninetales:
    primary: '#DDCA6B'
    secondary: '#737358'
    tertiary: '#AA7BD9'
    unibody: '#F2F3BA'

  # 081
  magnemite:
    primary: '#93928E'
    secondary: '#1A2342'
    tertiary: '#7E6A85'
    unibody: '#9DBBC5'

  # 258
  mudkip:
    primary: '#E0A142'
    secondary: '#05182A'
    tertiary: '#600060'
    unibody: '#32A1E4'

misty:
  # 055
  psyduck:
    primary: '#66431b'
    secondary: '#623108'
    tertiary: '#C16200'
    unibody: '#FFD54B'

  # 060
  poliwag:
    primary: '#C8DAE8'
    secondary: '#060329'
    tertiary: '#94C6FF'
    unibody: '#5B89BD'

  # 061
  poliwhirl:
    primary: '#E0E4EF'
    secondary: '#060329'
    tertiary: '#94C6FF'
    unibody: '#5C86B8'

  # 118
  goldeen:
    primary: '#DE6339'
    secondary: '#000000'
    tertiary: '#006FB2'
    unibody: '#F4F1F8'

  # 120
  staryu:
    primary: '#9E7438'
    secondary: '#2B1F0A'
    tertiary: '#FFFFFF'
    unibody: '#B1853C'

  # 121
  starmie:
    primary: '#8B869A'
    secondary: '#131117'
    tertiary: '#FFFFFF'
    unibody: '#A297B7'

  # 116
  horsea:
    primary: '#65AECF'
    secondary: '#3D616B'
    tertiary: '#D18CA1'
    unibody: '#86D4EB'

  # 130
  gyarados:
    primary: '#2E7090'
    secondary: '#113F58'
    tertiary: '#B2454B'
    unibody: '#307BA5'

surge:
  # 025
  pikachu:
    primary: '#F6BD20'
    secondary: '#4C1803'
    tertiary: '#DE7329'
    unibody: '#F7DE82'

  # 026
  raichu:
    primary: '#66431b'
    secondary: '#623108'
    tertiary: '#C16200'
    unibody: '#F2BD4B'

  # 125
  electabuzz:
    primary: '#0A162C'
    secondary: '#377B9C'
    tertiary: '#FCFBD8'
    unibody: '#F8D871'

  # 100 - electric
  voltorb:
    primary: '#000000'
    secondary: '#000000'
    tertiary: '#BAB608'
    unibody: '#ED2225'

  # 082
  magneton:
    primary: '#91918F'
    secondary: '#1A2342'
    tertiary: '#B5249A'
    unibody: '#A3BEC7'

erika:
  # 069
  bellsprout:
    primary: '#93CF9C'
    secondary: '#1F1E0C'
    tertiary: '#0078FC'
    unibody: '#DEDA6C'

  # 070
  weepinbell:
    primary: '#79B47C'
    secondary: '#786548'
    tertiary: '#0078FC'
    unibody: '#EBEB73'

  # 071
  victreebel:
    primary: '#88CA8D'
    secondary: '#DB8570'
    tertiary: '#66916C'
    unibody: '#EAEA6E'

  # 003
  venusaur:
    primary: '#548B52'
    secondary: '#C9F3F1'
    tertiary: '#142625'
    unibody: '#58A7A2'

  # 114
  tangela:
    primary: '#DF775E'
    secondary: '#1C384F'
    tertiary: '#FFFCFF'
    unibody: '#6697C0'

  # 044
  gloom:
    primary: '#A04041'
    secondary: '#000000'
    tertiary: '#FFFFFF'
    unibody: '#7796CD'

  # 102
  exeggcute:
    primary: '#D0B5BB'
    secondary: '#4F6666'
    tertiary: '#0CA8A8'
    unibody: '#F6D6D9'

  # 043
  oddish:
    primary: '#4D9242'
    secondary: '#19242C'
    tertiary: '#FFFFFF'
    unibody: '#587D9A'

koga:
  # 042
  golbat:
    primary: '#82487A'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#306E93'

  # 123
  scyther:
    primary: '#6A9B40'
    secondary: '#1D300C'
    tertiary: '#4C57B8'
    unibody: '#80C342'

  # 109
  koffing:
    primary: '#726487'
    secondary: '#472F6B'
    tertiary: '#BA517F'
    unibody: '#A793C6'

  # 110
  weezing:
    primary: '#897B88'
    secondary: '#3B3345'
    tertiary: '#FFF9B4'
    unibody: '#B1A4C2'

  # 089
  muk:
    primary: '#775A92'
    secondary: '#23182E'
    tertiary: '#DEC9A0'
    unibody: '#8D6DAC'

  # 048
  venonat:
    primary: '#C5598B'
    secondary: '#1E1B33'
    tertiary: '#51275C'
    unibody: '#615A90'

  # 049
  venomoth:
    primary: '#6E6991'
    secondary: '#373737'
    tertiary: '#FFFFFF'
    unibody: '#A59CC7'

sabrina:
 # 063
  abra:
    primary: '#DAC25E'
    secondary: '#4F4A34'
    tertiary: '#A5978B'
    unibody: '#F1D95F'

  # 064
  kadabra:
    primary: '#CAB43A'
    secondary: '#4F4A34'
    tertiary: '#A5978B'
    unibody: '#F4E154'

  # 065
  alakazam:
    primary: '#D8BF58'
    secondary: '#4F4A34'
    tertiary: '#A5978B'
    unibody: '#EAD055'

  # 122
  mr.mime:
    primary: '#183F5E'
    secondary: '#C4798B'
    tertiary: '#73696B'
    unibody: '#F9E4E9'

  # 049
  venomoth:
    primary: '#6E6991'
    secondary: '#373737'
    tertiary: '#FFFFFF'
    unibody: '#A59CC7'

blaine:
  # 038
  ninetales:
    primary: '#DDCA6B'
    secondary: '#737358'
    tertiary: '#AA7BD9'
    unibody: '#F2F3BA'

  # 058
  growlithe:
    primary: '#8B7963'
    secondary: '#4F3215'
    tertiary: '#285DB2'
    unibody: '#DB9651'

  # 059
  arcanine:
    primary: '#EA5F24'
    secondary: '#665836'
    tertiary: '#FF9C04'
    unibody: '#FEE3A0'

  # 077
  ponyta:
    primary: '#E86946'
    secondary: '#1F1C15'
    tertiary: '#715DD1'
    unibody: '#EADCB7'

  # 078
  rapidash:
    primary: '#DF533C'
    secondary: '#1F1C15'
    tertiary: '#5B4BA8'
    unibody: '#F5EFBF'

  # 126
  magmar:
    primary: '#F9DC64'
    secondary: '#07050F'
    tertiary: '#003985'
    unibody: '#D84E27'

  # 112
  rhydon:
    primary: '#E7CEB8'
    secondary: '#434957'
    tertiary: '#00FAE9'
    unibody: '#99A0B0'

giovanni:
  # 095
  onix:
    primary: '#4B494E'
    secondary: '#E8E8D6'
    tertiary: '#4E7378'
    unibody: '#9B9AA2'

  # 033
  nidorino:
    primary: '#6AA19E'
    secondary: '#3A243E'
    tertiary: '#89D7BF'
    unibody: '#A47DA9'

  # 034
  nidoking:
    primary: '#518286'
    secondary: '#3A243E'
    tertiary: '#89D7BF'
    unibody: '#A86EA1'

  # 031
  nidoqueen:
    primary: '#597E98'
    secondary: '#111742'
    tertiary: '#AD7561'
    unibody: '#81ABC3'

  # 068
  machamp:
    primary: '#8A9AA9'
    secondary: '#202C2E'
    tertiary: '#C22C2E'
    unibody: '#9DAEC0'

  # 053
  persian:
    primary: '#514A40'
    secondary: '#0048C4'
    tertiary: '#000000'
    unibody: '#F4E2B2'

  # 051
  dugtrio:
    primary: '#E1AECD'
    secondary: '#38291E'
    tertiary: '#FFFFFF'
    unibody: '#92745C'

  # 111
  rhyhorn:
    primary: '#958F99'
    secondary: '#3C393E'
    tertiary: '#FF7700'
    unibody: '#B6ADBE'

  # 115
  kangaskhan:
    primary: '#EFE9AB'
    secondary: '#000000'
    tertiary: '#D98067'
    unibody: '#8D746D'

lorelei:
  # 080
  slowbro:
    primary: '#BACBD2'
    secondary: '#8B5A18'
    tertiary: '#7B2031'
    unibody: '#DD9DAE'

  # 087
  dewgong:
    primary: '#BFC1D6'
    secondary: '#282B32'
    tertiary: '#FF6482'
    unibody: '#D6DCEA'

  # 091
  cloyster:
    primary: '#262336'
    secondary: '#48416B'
    tertiary: '#FFFF00'
    unibody: '#837A95'

  # 124
  jynx:
    primary: '#CB313B'
    secondary: '#110919'
    tertiary: '#28A651'
    unibody: '#552B7F'

  # 131
  lapras:
    primary: '#157397'
    secondary: '#00222E'
    tertiary: '#C26837'
    unibody: '#0793C6'

  # 086
  seel:
    primary: '#D4DDEC'
    secondary: '#33373B'
    tertiary: '#FF6482'
    unibody: '#EAEFF3'

  # 090
  shellder:
    primary: '#221E1F'
    secondary: '#48416B'
    tertiary: '#FFFFFF'
    unibody: '#867DB2'

bruno:
  # 095
  onix:
    primary: '#4B494E'
    secondary: '#E8E8D6'
    tertiary: '#4E7378'
    unibody: '#9B9AA2'

  # 106
  hitmonlee:
    primary: '#302C2B'
    secondary: '#171210'
    tertiary: '#43D2B4'
    unibody: '#9F8880'

  # 107
  hitmonchan:
    primary: '#C66961'
    secondary: '#1F1B17'
    tertiary: '#FFF9F2'
    unibody: '#C2B5A5'

  # 068
  machamp:
    primary: '#8A9AA9'
    secondary: '#202C2E'
    tertiary: '#C22C2E'
    unibody: '#9DAEC0'

  # 066
  machop:
    primary: '#94ADB2'
    secondary: '#202C2E'
    tertiary: '#C22C2E'
    unibody: '#A6C7CE'

  # 076
  golem:
    primary: '#494441'
    secondary: '#B74345'
    tertiary: '#FFBCD3'
    unibody: '#898E88'

  # 090
  shellder:
    primary: '#221E1F'
    secondary: '#48416B'
    tertiary: '#FFFFFF'
    unibody: '#867DB2'

agatha:
  # 094
  gengar:
    primary: '#EF735B'
    secondary: '#43B28F'
    tertiary: '#BB4477'
    unibody: '#4B294A'

  # 042
  golbat:
    primary: '#82487A'
    secondary: '#F5F56E'
    tertiary: '#5C421B'
    unibody: '#306E93'

  # 024
  arbok:
    primary: '#3A3839'
    secondary: '#F5F5F5'
    tertiary: '#BB4477'
    unibody: '#A7A1BD'

  # 092
  gastly:
    primary: '#0C0D22'
    secondary: '#7A0046'
    tertiary: '#FFBC00'
    unibody: '#7D6EB3'

  # 093
  haunter:
    primary: '#ED779A'
    secondary: '#242033'
    tertiary: '#FFBC00'
    unibody: '#7D6EB3'

lance:
  # 148
  dragonair:
    primary: '#5577BB'
    secondary: '#E8F0F4'
    tertiary: '#D9D9D9'
    unibody: '#77A2D5'

  # 149
  dragonite:
    primary: '#2DAD9C'
    secondary: '#4C351B'
    tertiary: '#6D42BE'
    unibody: '#F2B36E'

  # 142
  aerodactyl:
    primary: '#8167AE'
    secondary: '#20153B'
    tertiary: '#E9E2FF'
    unibody: '#A5B2DC'

  # 006
  charizard:
    primary: '#CF844B'
    secondary: '#4C1803'
    tertiary: '#DBD8AE'
    unibody: '#DC8E4C'

  # 129
  magikarp:
    primary: '#F8C471'
    secondary: '#632A1E'
    tertiary: '#000000'
    unibody: '#F17960'

  # 130
  gyarados:
    primary: '#2E7090'
    secondary: '#113F58'
    tertiary: '#B2454B'
    unibody: '#307BA5'

gary:
  # 007
  squirtle:
    primary: '#916A5B'
    secondary: '#832900'
    tertiary: '#B4E6EE'
    unibody: '#84C1D4'

  # 008
  wartortle:
    primary: '#C8E8F5'
    secondary: '#2D333D'
    tertiary: '#AF8C71'
    unibody: '#A8BDE2'

  # 009
  blastoise:
    primary: '#4D5D6C'
    secondary: '#42341C'
    tertiary: '#B7D9FF'
    unibody: '#85ACD7'

  # 034
  nidoking:
    primary: '#518286'
    secondary: '#3A243E'
    tertiary: '#89D7BF'
    unibody: '#A86EA1'

  # 059
  arcanine:
    primary: '#EA5F24'
    secondary: '#665836'
    tertiary: '#FF9C04'
    unibody: '#FEE3A0'

  # 031
  nidoqueen:
    primary: '#597E98'
    secondary: '#111742'
    tertiary: '#AD7561'
    unibody: '#81ABC3'

  # 076
  golem:
    primary: '#494441'
    secondary: '#B74345'
    tertiary: '#FFBCD3'
    unibody: '#898E88'

  # 127
  pinsir:
    primary: '#6C6260'
    secondary: '#60067D'
    tertiary: '#FFFFFF'
    unibody: '#B7A8A5'

  # 022
  fearow:
    primary: '#DC6859'
    secondary: '#301515'
    tertiary: '#E5C0C0'
    unibody: '#AD7542'

  # 065
  alakazam:
    primary: '#D8BF58'
    secondary: '#4F4A34'
    tertiary: '#A5978B'
    unibody: '#EAD055'

  # 133
  eevee:
    primary: '#603E18'
    secondary: '#000000'
    tertiary: '#4D3C9E'
    unibody: '#C08C5C'

  # 098
  krabby:
    primary: '#E78A4F'
    secondary: '#292929'
    tertiary: '#367382'
    unibody: '#F4E5E0'

  # 084
  doduo:
    primary: '#45464A'
    secondary: '#FFFFFF'
    tertiary: '#006AD4'
    unibody: '#CB9573'

  # 085
  dodrio:
    primary: '#484647'
    secondary: '#FFFFFF'
    tertiary: '#006AD4'
    unibody: '#C99877'

  # 126
  magmar:
    primary: '#F9DC64'
    secondary: '#07050F'
    tertiary: '#003985'
    unibody: '#D84E27'

jessie:
  # 108
  lickitung:
    primary: '#E4B9CA'
    secondary: '#693F45'
    tertiary: '#589196'
    unibody: '#EBA5B0'

  # 052
  meowth:
    primary: '#434343'
    secondary: '#0048C4'
    tertiary: '#000000'
    unibody: '#F4EDD1'

  # 024
  arbok:
    primary: '#3A3839'
    secondary: '#F5F5F5'
    tertiary: '#BB4477'
    unibody: '#A7A1BD'

james:
  # 052
  meowth:
    primary: '#434343'
    secondary: '#0048C4'
    tertiary: '#000000'
    unibody: '#F4EDD1'

  # 058
  growlithe:
    primary: '#8B7963'
    secondary: '#4F3215'
    tertiary: '#285DB2'
    unibody: '#DB9651'

  # 109
  koffing:
    primary: '#726487'
    secondary: '#472F6B'
    tertiary: '#BA517F'
    unibody: '#A793C6'

  # 110
  weezing:
    primary: '#897B88'
    secondary: '#3B3345'
    tertiary: '#FFF9B4'
    unibody: '#B1A4C2'

  # 129
  magikarp:
    primary: '#F8C471'
    secondary: '#632A1E'
    tertiary: '#000000'
    unibody: '#F17960'

  # 130
  gyarados:
    primary: '#2E7090'
    secondary: '#113F58'
    tertiary: '#B2454B'
    unibody: '#307BA5'

  # 070
  weepinbell:
    primary: '#79B47C'
    secondary: '#786548'
    tertiary: '#0078FC'
    unibody: '#EBEB73'

  # 071
  victreebel:
    primary: '#88CA8D'
    secondary: '#DB8570'
    tertiary: '#66916C'
    unibody: '#EAEA6E'
